"""Add status field to document

Revision ID: 13763b17bfd7
Revises: 305aee140c07
Create Date: 2026-06-18 22:40:36.259022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13763b17bfd7'
down_revision: Union[str, Sequence[str], None] = '305aee140c07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('status', sa.String(length=50), server_default='uploaded', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'status')
    # ### end Alembic commands ###
