"""add_citations_to_chat_messages

Revision ID: 13b8700bfd80
Revises: aa7284ed317a
Create Date: 2026-06-27 10:42:26.195967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13b8700bfd80'
down_revision: Union[str, Sequence[str], None] = 'aa7284ed317a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('citations', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_messages', 'citations')
    # ### end Alembic commands ###
